[project]
name = "datashuttle"
version = "0.0.0"
description = "Organise and transfer scientific projects in BIDS format"
readme = "README.md"
requires-python = ">=3.9.0"

authors = [
    {name = "Joe Ziminski", email = "j.ziminski@ucl.ac.uk"},
    {name = "Adam Tyson", email = "code@adamltyson.com"},
    {name = "Niko Sirmpilatze", email = "n.sirmpilatze@ucl.ac.uk"},
]


dependencies = [
    "appdirs",
    "paramiko",
    "PyYAML",
    "requests",
    "rich",
]


[project.optional-dependencies]
dev = [
    "black",
    "pytest-cov",
    "pytest",
    "coverage",
    "bump2version",
    "pre-commit",
    "flake8",
    "isort",
    "mypy",
    "simplejson",
    "types-requests",
    "types-PyYAML",
    "types-appdirs",
    "types-paramiko",
    "types-simplejson",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
datashuttle = "datashuttle.command_line_interface:main"

[tool.pytest.ini_options]
addopts = "--cov=datashuttle"

[tool.isort]
profile = "black"

[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = false
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
