[project]
name = "datashuttle"
version = "0.0.0"
description = "Organise and transfer scientific projects in BIDS format"
readme = "README.md"
requires-python = ">=3.9.0"

authors = [
    {name = "Joe Ziminski", email = "j.ziminski@ucl.ac.uk"},
    {name = "Adam Tyson", email = "code@adamltyson.com"},
    {name = "Niko Sirmpilatze", email = "n.sirmpilatze@ucl.ac.uk"},
]


dependencies = [
    "appdirs",
    "ftpsync",
    "pyftpsync @ git+ssh://git@github.com/JoeZiminski/pyftpsync.git#open_api_to_private_key",
    "paramiko",
    "pytest",
    "PyYAML",
]


[project.optional-dependencies]
dev = [
    "black",
    "pytest-cov",
    "pytest",
    "coverage",
    "bump2version",
    "pre-commit",
    "flake8",
]


[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = false
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''


[tool.flake8]
# Ignores - https://lintlyci.github.io/Flake8Rules
# W291 trailing whitespace
# E731 do not assign a lambda expression, use a def
# W293 blank line contains whitespace
# E203  Whitespace before ':'  (sometimes conflicts with black)
# E501 line too long (84 > 79 characters)  (sometimes too annoying)
# W503	Line break occurred before a binary operator
# C901 McCabe complexity test. Would be nice to reenable, but takes work
ignore = ["E203", "W503", "E501", "E731", "C901", "W291", "W293", "E402", "E722"]
max-line-length = 79
max-complexity = 18
per-file-ignores = [
    '__init__.py:F401',
]


