name: tests

on: [push] #[push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]  # ubuntu-latest, macos-latest,
        python-version: [ "3.9", "3.10" ] # "3.7","3.8",
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint
        run: |
          black ./ --check -l 79
          flake8
          isort

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # ubuntu-latest, macos-latest, windows-latest,
        python-version: ["3.9", "3.10"] # "3.7","3.8",
#        exclude:
#          - os: windows-latest
#            python-version: 3.9
#          - os: macos-latest
#            python-version: 3.7
#          - os: macos-latest
#            python-version: 3.8
#          - os: macos-latest
#            python-version: 3.9
#          - os: windows-latest
#            python-version: 3.7
#          - os: windows-latest
#            python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
#          auto-activate-base: true
          channels: conda-forge
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - name: Install RClone
        run: conda install -c conda-forge rclone
#      - name: Set up Python
 #       uses: actions/setup-python@v2
  #      with:
   #       python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test
        run: pytest
#      - name: Coveralls
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#            pip install coveralls
#            coveralls --service=github
#  deploy:
#    needs: test
#    runs-on: ubuntu-latest
#    if: contains(github.ref, 'tags')
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python
#        uses: actions/setup-python@v1
#        with:
#          python-version: "3.x"
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -U build twine
#      - name: Build and publish
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
#        run: |
#          python -m build
 #         twine upload dist/*
